#
# Makefile
#

CIBUILD		?= false
BUILD_TYPE	?= Debug
PROJECT_DIR	:= $(PWD)
DRY_RUN		?= true

ifeq ($(CIBUILD), true)
    BUILD_TYPE = Release
    DRY_RUN = false
endif

.PHONY: setup update lint pregen postgen autogenerated format scene

setup:
	$(PROJECT_DIR)/scripts/setup ${BUILD_TYPE}

update:
	$(PROJECT_DIR)/scripts/update

lint:
	$(PROJECT_DIR)/scripts/lint

pregen:
	$(PROJECT_DIR)/scripts/pregen

postgen:
	$(PROJECT_DIR)/scripts/postgen

format:
	$(PROJECT_DIR)/scripts/format